import pyautogui as aut
aut.press("win")
aut.moveTo(796,783)
aut.click()
aut.sleep(2)
#aut.mouseInfo()
aut.moveTo(779,14)
aut.sleep(2)
aut.click()
aut.hotkey("win", "d")
aut.sleep(2)
aut.click()
aut.moveTo(4,939)
aut.sleep(2)
aut.doubleClick()
